# fly.toml app configuration file generated for questly on 2025-11-06T14:55:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'questly'
primary_region = 'iad'
swap_size_mb = 512

[env]
  PORT = 8080
  DATA_DIR = "/data"
  SWIM_PORT = 8787
  PUBSUB_PORT = 1337
  KV_PORT = 1773

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.api_http]
    grace_period = '30s'
    interval = '15s'
    method = 'GET'
    path = '/health'
    port = 8080
    timeout = '10s'
    type = 'http'

  [checks.swim_http]
    grace_period = '30s'
    interval = '15s'
    method = 'GET'
    path = '/health'
    port = 8787
    timeout = '10s'
    type = 'http'

  [checks.pubsub_http]
    grace_period = '30s'
    interval = '15s'
    method = 'GET'
    path = '/health'
    port = 1337
    timeout = '10s'
    type = 'http'

  [checks.kv_http]
    grace_period = '30s'
    interval = '15s'
    method = 'GET'
    path = '/health'
    port = 1773
    timeout = '10s'
    type = 'http'
